export const SET_CREATE_ORDER_REQUESt = 'SET_CREATE_ORDER_REQUESt'
export const SET_CREATE_ORDER_SUCCESS = 'SET_CREATE_ORDER_SUCCESS'
export const SET_CREATE_ORDER_FAIL = 'SET_CREATE_ORDER_FAIL'


export const SET_GET_ORDER_REQUEST = 'SET_GET_ORDER_REQUEST'
export const SET_GET_ORDER_SUCCESS = 'SET_GET_ORDER_SUCCESS'
export const SET_GET_ORDER_FAIL = 'SET_GET_ORDER_FAIL'


export const SET_ORDER_PAY_REQUEST = 'SET_ORDER_PAY_REQUEST'
export const SET_ORDER_PAY_SUCCESS = 'SET_ORDER_PAY_SUCCESS'
export const SET_ORDER_PAY_FAIL = 'SET_ORDER_PAY_FAIL'
export const SET_ORDER_RESET = 'SET_ORDER_RESET'



export const SET_GET_ORDERS_REQUEST = 'SET_GET_ORDERS_REQUEST'
export const DISPLAY_ORDERS_SUCCESS = 'DISPLAY_ORDERS_SUCCESS'
export const SET_ORDERS_FAIL = 'SET_ORDERS_FAIL'


export const ORDER_LIST_RESET = 'ORDER_LIST_RESET'

export const ORDERS_REQUEST = 'ORDERS_REQUEST'
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS'
export const ORDERS_FAIL = 'ORDERS_FAIL'