export const SET_PRODUCT_LIST_REQUEST = 'SET_PRODUCT_LIST_REQUEST'
export const SET_PRODUCT_LIST_SUCCESS = 'SET_PRODUCT_LIST_SUCCESS'
export const SET_PRODUCT_LIST_FAIL = 'SET_PRODUCT_LIST_FAIL'
export const SET_FETCH_SINGLE_PRODUCT = 'SET_FETCH_SINGLE_PRODUCT'
export const SET_FETCH_SINGLE_PRODUCT_FAIL = 'SET_FETCH_SINGLE_PRODUCT_FAIL'
export const SET_FETCH_SINGLE_PRODUCT_REQUEST = 'SET_FETCH_SINGLE_PRODUCT_REQUEST'


export const SET_PRODUCT_DELETE_SUCCESS = 'SET_PRODUCT_DELETE_SUCCESS'
export const SET_PRODUCT_DELETE_FAIL = 'SET_PRODUCT_DELETE_FAIL'

export const SET_CREATE_PRODUCT_SUCCESS = 'SET_CREATE_PRODUCT_SUCCESS'
export const SET_CREATE_PRODUCT_FAIL = 'SET_CREATE_PRODUCT_FAIL'
export const SET_CREATE_PRODUCT_RESET = 'SET_CREATE_PRODUCT_RESET'


export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'


export const PRODUCT_CREATE_REVIEW_REQUEST = 'PRODUCT_CREATE_REVIEW_REQUEST'
export const PRODUCT_CREATE_REVIEW_SUCCESS = 'PRODUCT_CREATE_REVIEW_SUCCESS'
export const PRODUCT_CREATE_REVIEW_FAIL = 'PRODUCT_CREATE_REVIEW_FAIL'
export const PRODUCT_CREATE_REVIEW_RESET = 'PRODUCT_CREATE_REVIEW_RESET'


export const PRODUCT_TOP_RATED_SUCCESS = 'PRODUCT_TOP_RATED_SUCCESS'
export const PRODUCT_TOP_RATED_REQUEST = 'PRODUCT_TOP_RATED_REQUEST'
export const PRODUCT_TOP_RATED_FAIL = 'PRODUCT_TOP_RATED_FAIL'