export const SET_USER_LOGIN_REQUEST = 'SET_USER_LOGIN_REQUEST'
export const SET_USER_LOGIN_SUCCESS = 'SET_USER_LOGIN_SUCCESS'
export const SET_USER_LOGIN_FAIL = 'SET_USER_LOGIN_FAIL'
export const SET_USER_LOGOUT = 'SET_USER_LOGOUT'



export const SET_USER_REGISTER_REQUEST = 'SET_USER_REGISTER_REQUEST'
export const SET_USER_REGISTER_SUCCESS = 'SET_USER_REGISTER_SUCCESS'
export const SET_USER_REGISTER_FAIL = 'SET_USER_REGISTER_FAIL'



export const SET_USER_USER_DETAILS_SUCCESS = 'SET_USER_USER_DETAILS_SUCCESS'
export const SET_USER_USER_DETAILS_FAIL = 'SET_USER_USER_DETAILS_FAIL'
export const SET_USER_USER_DETAILS_REQUEST = 'SET_USER_USER_DETAILS_REQUEST'
export const SET_USER_USER_DETAILS_RESET = 'SET_USER_USER_DETAILS_RESET'


export const SET_USER_UPDATE_PROFILE_SUCCESS = 'SET_USER_UPDATE_PROFILE_SUCCESS'
export const SET_USER_UPDATE_PROFILE_FAIL = 'SET_USER_UPDATE_PROFILE_FAIL'
export const SET_USER_UPDATE_PROFILE_REQUEST = 'SET_USER_UPDATE_PROFILE_REQUEST'
export const SET_USER_RESET = 'SET_USER_RESET'


export const SET_USER_LIST_REQUEST = 'SET_USER_LIST_REQUEST'
export const SET_USER_LIST_SUCCESS = 'SET_USER_LIST_SUCCESS'
export const SET_USER_LIST_FAIL = 'SET_USER_LIST_FAIL'
export const SET_USER_LIST_RESET = 'SET_USER_LIST_RESET'


export const SET_USER_LIST_DELETED_SUCCESS = 'SET_USER_LIST_DELETED_SUCCESS'
export const SET_USER_LIST_DELETED_FAIL = 'SET_USER_LIST_DELETED_FAIL'
export const SET_USER_LIST_DELETED_REQUEST = 'SET_USER_LIST_DELETED_REQUEST'

export const SET_USER_INFORMATION_SUCCESS = 'SET_USER_INFORMATION_SUCCESS'
export const SET_USER_INFORMATION_FAIL = 'SET_USER_INFORMATION_FAIL'

export const SET_USER_UPDATE_SUCCESS = 'SET_USER_UPDATE_SUCCESS'
export const SET_USER_UPDATE_FAIL = 'SET_USER_UPDATE_FAIL'
export const SET_USER_UPDATE_RESET = 'SET_USER_UPDATE_RESET'